# Generated by Django 5.1.1 on 2025-03-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0002_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
