# Generated by Django 5.1.7 on 2025-03-31 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0003_customuser_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['option_label']},
        ),
        migrations.RemoveField(
            model_name='test',
            name='category',
        ),
        migrations.AddField(
            model_name='test',
            name='categories',
            field=models.ManyToManyField(to='code_nest.category'),
        ),
    ]
