# Generated by Django 5.1.7 on 2025-05-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0006_course_image_course_is_published_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='image',
            field=models.ImageField(default='tests/default.png', upload_to='tests/'),
        ),
    ]
