# Generated by Django 5.1.7 on 2025-05-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0007_test_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(default='tests/default_image.png', upload_to='tests/'),
        ),
    ]
