# Generated by Django 5.1.1 on 2025-05-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0009_alter_test_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.DurationField(default='00:30:00', help_text='Duration in HH:MM:SS format'),
        ),
    ]
