# Generated by Django 5.1.1 on 2025-05-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0010_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.DurationField(default='00:30:00'),
        ),
    ]
