# Generated by Django 5.1.1 on 2025-05-10 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0012_testattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='percentage',
            field=models.FloatField(default=0),
        ),
    ]
