# Generated by Django 5.1.1 on 2025-05-10 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0013_testresult_completed_testresult_percentage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAttempt',
        ),
    ]
