# Generated by Django 5.1.1 on 2025-05-10 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0014_delete_testattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testresults', to=settings.AUTH_USER_MODEL),
        ),
    ]
