# Generated by Django 5.1.7 on 2025-05-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0015_alter_testresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
