# Generated by Django 5.1.1 on 2025-05-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0017_testresult_cooldown_until'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_highest_score',
            field=models.BooleanField(default=False),
        ),
    ]
