# Generated by Django 5.1.1 on 2025-05-12 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0018_alter_testresult_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'get_latest_by': 'date_taken', 'ordering': ['-date_taken']},
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='is_highest_score',
        ),
    ]
