# Generated by Django 5.1.1 on 2025-05-12 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0019_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-date_taken']},
        ),
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together={('user', 'test')},
        ),
    ]
