# Generated by Django 5.1.1 on 2025-05-12 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0022_alter_testresult_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testresult',
            unique_together=set(),
        ),
    ]
