# Generated by Django 5.1.1 on 2025-05-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0025_useranswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='code_nest.answer'),
        ),
    ]
