# Generated by Django 5.1.1 on 2025-05-13 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_nest', '0026_alter_useranswer_selected_answer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user', 'question', 'test_result')},
        ),
    ]
